version: 2.1


executor:
  name: node/default
  tag: '12.16.1'
  docker: circleci/node:12.16.1

jobs:
  build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1.4-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1.4-{{ .Branch }}-
            - yarn-packages-v1.4-
      - run:
          name: Install Dependencies
          command: |
            yarn install
      - save_cache:
          paths:
            - ~/project/node_modules
          key: yarn-packages-v1.4-{{ .Branch }}-{{ checksum "yarn.lock" }}

  test:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1.4-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1.4-{{ .Branch }}-
            - yarn-packages-v1.4-
      - run:
          name: Testing
          command: yarn test

  gatsby-build:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - restore_cache:
          keys:
            # when lock file changes, use increasingly general patterns to restore cache
            - yarn-packages-v1.4-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1.4-{{ .Branch }}-
            - yarn-packages-v1.4-
      - run:
          name: Build Gatsby
          command: |
            sudo npm install -g gatsby-cli
            gatsby build
      - persist_to_workspace:
          root: ~/project
          paths:
            - public

  deploy:
    docker:
      - image: circleci/node:12.16.1
    steps:
      - checkout
      - attach_workspace:
          at: ~/project
      - run:
          name: Deploy
          command: |
            sudo npm install -g firebase-tools
            firebase deploy --token $FIREBASE_TOKEN
workflows:
  version: 2
  all_in_one:
    jobs:
      - build
      - test:
          requires:
            - build
      - gatsby-build:
          requires:
            - test
      - deploy:
          requires:
            - gatsby-build
          filters:
            branches:
              only: master
